[package]
name = "jfix"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
env_logger = "0.11"

clap = {version = "4.5", features = ["derive", "unicode", "suggestions"]}

serde_json = "1.0"
json-repair = "0.4.0"
